# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QL9ElYibda1SzcrwAU9qil1q3dfKjpHE
"""

!pip install tensorflow streamlit pyngrok pillow numpy opencv-python

import streamlit as st
import tensorflow as tf
import numpy as np
from PIL import Image

st.title("🌿 AgroDetect AI – Plant Disease Detection")

model = tf.keras.models.load_model("agrodetect_model.keras")

class_names = ["Apple Scab","Apple Black Rot","Corn Rust","Healthy"]

def preprocess(image):
    image = image.resize((224,224))
    img = np.array(image)/255.0
    return np.expand_dims(img,0)

file = st.file_uploader("Upload Leaf Image", type=["jpg","jpeg","png"])

if file:
    image = Image.open(file)
    st.image(image, width=300)

    img = preprocess(image)
    pred = model.predict(img)
    idx = np.argmax(pred)

    st.subheader(f"Prediction: {class_names[idx]}")